[package]
name = "transistor"
version = "0.1.0"
license = "Beerware"
authors = ["luftaquila <mail@luftaquila.io>"]
repository = "https://github.com/luftaquila/transistor"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3"
directories = "5.0"
display-info = "0.5"
mouce = "0.2"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }

winit = "0.28"
pixels = "0.13"
