name: Rust

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build server
      run: cargo build --bin transistor-server --verbose
    - name: Build client
      run: cargo build --bin transistor-client --verbose

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install -y libxi-dev libxtst-dev
    - name: Build server
      run: xvfb-run cargo build --bin transistor-server --verbose
    - name: Build client
      run: xvfb-run cargo build --bin transistor-client --verbose

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build server
      run: cargo build --bin transistor-server --verbose
    - name: Build client
      run: cargo build --bin transistor-client --verbose
